MAINTAINER par.nils.amsen@gmail.com

FROM mysql/latest

ENV MYSQL_ROOT_PASSWORD local
ENV MYSQL_DATABASE local
ENV MYSQL_USER local
ENV MYSQL_PASSWORD local

VOLUME /www/db-be-mysql:/var/lib/mysql

RUN apt-get update
