---
- hosts: paramsendotcom
  remote_user: root
  tasks:
      - name: "Disable root user login"
        lineinfile: dest=/etc/ssh/sshd_config
            regexp="^PermitRootLogin.*"
            line="PermitRootLogin no"
            state=present
        notify: "Restart ssh"

      - name: "Disable password login"
        lineinfile: dest=/etc/ssh/sshd_config
          regexp="^PasswordAuthentication.*"
          line="PasswordAuthentication no"
          state=present
        notify: "Restart ssh"
        
  handlers: 
    - name: "Restart ssh"
      service: name=ssh state=restarted