---
- hosts: paramsendotcom
  vars_files:
      - vars/private_user.yml
  remote_user: root
  tasks: 
    - name: "Add www user"
      user: name=www
        password={{ www_password_hash }}
        groups=docker
        shell=/bin/bash

    - name: "Add deploy user to www group"
      user: name=deploy append=yes groups=www

    - name: "Copy private key for ssh login"
      authorized_key: user=deploy key="{{ lookup('file', '{{ www_ssh_key_path }}') }}"

    - name: "Create /www folder tree"
      file: path={{ item }} state=directory
      with_items: 
        - "/www"
        - "/www/public"
        - "/www/db"

    - name: "ensure github.com is a known host"
      lineinfile: dest=/root/.ssh/known_hosts
        state=present
        line="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp="^github\\.com"

    - name: "Pull paramsendotcom git repo"
      git: repo=https://github.com/paramsen/root.paramsen.com.git
        dest=/www/paramsendotcom
        accept_hostkey=yes

    - name: "Permission /www"
      file: path=/www state=directory owner=deploy group=www mode=g+r recurse=yes

    - name: "Permission /www/db"
      file: path=/www/db state=directory owner=deploy group=www mode=g+rw recurse=yes

    - name: "Copy environment variables"
      copy: src=files/private_env.sh dest=/etc/profile.d/env.sh
