---
- hosts: paramsendotcom
  vars_files:
      - vars/private_user.yml
      - vars/apt_packages.yml
  remote_user: root
  tasks:
      - name: "Create unprivileged deploy user, add to sudo group for privilege escalation"
        user: name=deploy
            password={{ deploy_password_hash }}
            groups=sudo
            shell=/bin/bash
            
      - name: "Copy private key for ssh login"
        authorized_key: user=deploy key="{{ lookup('file', '{{ deploy_ssh_key_path }}') }}"

      - name: "Install security packages"
        apt: state=installed pkg={{ item }}
        with_items: "{{ apt_security_packages }}"

      - name: "Set apt periodic security updates"
        copy: src=files/apt_periodic.conf dest=/etc/apt/apt.conf.d/10periodic

      - name: "Setup ufw"
        ufw: state=enabled policy=deny

      - name: "Set ufw to allow ssh"
        ufw: rule=allow port=22 proto=tcp