Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.network 'forwarded_port', guest: 80, host: 8088
  config.vm.network 'private_network', ip: '192.168.33.10'
  config.vm.synced_folder '../', '/www'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '1024'
    # For NAT adapter
    vb.customize ['modifyvm', :id, '--nictype1', 'Am79C973']
    # For host-only adapter
    vb.customize ['modifyvm', :id, '--nictype2', 'Am79C973']
  end

  config.vm.provision 'shell',  inline: <<-SHELL
    echo "Fix \"stdout is not a tty\" prompt"
    sudo sed '$ s/.*/tty -s \&\&\ mesg n/' -r /root/.profile > /root/.profile.temp
    sudo mv /root/.profile.temp /root/.profile

    containers=$(docker ps -a | awk  '{ if (NR > 1) { print $2; } }')
    echo "Stop->Remove docker containers: $containers"

    docker stop $containers
    docker rm $(docker ps -a | awk  '{ if (NR > 1) { print $2; } }')

    sudo apt-get update
  SHELL

  config.vm.provision 'docker' do |d|
    d.build_image '/www/modules/db-be-mysql', args: '-t db-be-mysql'
    # TODO: d.build_image "/www/modules/nginx", args: "-t nginx"
    d.build_image '/www/modules/www-be', args: '-t www-be'
    # TODO: d.build_image "/www/modules/www-fe", args: "-t www-fe"
    d.run 'db-be-mysql', auto_assign_name: true
    d.run 'www-be', auto_assign_name: true, args: '--link db-be-mysql:db-be-mysql'
  end
end
