version: '2'

services:
  be:
    extends:
      file: ../be/docker/docker-compose.yml
      service: be
    volumes:
      - '/www/public:/www/public'
    environment:
      - NODE_ENV=$NODE_ENV
    restart: always
    depends_on: 
      - db

  db: 
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - '../nginx:/etc/nginx:ro'
    ports:
      - '80:80'
    depends_on: 
      - be