export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL';
export const GET_ARTICLE_DETAIL_SUCCESS = 'GET_ARTICLE_DETAIL_SUCCESS';

export const BROWSER_HISTORY_CHANGE = 'BROWSER_HISTORY_CHANGE';