---
- hosts: paramsendotcom
  remote_user: root
  vars_files: 
    - "../vars/private_www_env.yml"
  environment: "{{ env_vars }}"
  become_user: www
  become_method: su
  tasks:
    - name: "Pull repo"
      git: repo=https://github.com/paramsen/root.paramsen.com.git
        dest=/www/paramsendotcom
        accept_hostkey=yes
        force=yes

    - name: "Stop docker containers"
      shell: docker-compose stop
        chdir=/www/paramsendotcom/modules/run/prod
      become: true

    - name: "Rebuild & run docker containers"
      shell: docker-compose up --build -d
        chdir=/www/paramsendotcom/modules/run/prod
      become: true
