---
- hosts: paramsendotcom
  remote_user: deploy
  vars_files: 
    - "../vars/private_www_env.yml"
  environment: "{{ env_vars }}"
  tasks:
    - name: "Pull repo"
      git: repo=https://github.com/paramsen/root.paramsen.com.git
        dest=/www/paramsendotcom
        accept_hostkey=yes
        force=yes

    - name: "Permission /www/paramsendotcom/.../fe/code script execution"
      file: path=/www/paramsendotcom/modules/fe/code/{{ item }} state=touch owner=deploy group=www mode=u+x
      with_items: 
        - init.sh
        - build.sh
      become: true

    - name: "Build fe module npm dependencies"
      shell: ./build.sh
        chdir=/www/paramsendotcom/modules/fe/code

    - name: "Put build into /www/public"
      shell: mv build/* /www/public 
        chdir=/www/paramsendotcom/modules/fe/code
